"""Render a toy HTML page styled entirely by gzipt-generated CSS, for a blog
image. The :root design tokens come from the real corpus (so var() refs
resolve); every other rule is generated by gzipt and validated by tinycss2.

Run:  .venv/bin/python render_css.py   (then chromium screenshots demo.html)
"""

from __future__ import annotations

import re
import subprocess

import tinycss2

import css_experiment as C  # reuse STANDARD_PROPS / sane_value / valid_rules
import gzipt


def root_tokens(css: str) -> str:
    out = []
    for n in tinycss2.parse_stylesheet(css, skip_comments=True, skip_whitespace=True):
        if n.type == "qualified-rule" and tinycss2.serialize(n.prelude).strip() == ":root":
            out.append(tinycss2.serialize([n]).strip())
    return "\n".join(out)


def gather_rules(corpus: str, corpus_rules: set[str]):
    prompts = [b"body {\n  ", b"button {\n  ", b"a {\n  ", b"h1 {\n  ",
               b"h2 {\n  ", b"table {\n  ", b"ul {\n  ", b"blockquote {\n  ",
               b'input[type="radio"] {\n  ']
    chosen, seen = [], set()
    for pr in prompts:
        for seed in (1, 2, 3):
            out = gzipt.generate_spans(corpus.encode(), pr, length=1500,
                                       span_len=16, key=8, seed=seed)
            gen = pr.decode() + out.decode("utf-8", "replace")
            for ser, sel, nd in C.valid_rules(gen):
                if ser in seen:
                    continue
                seen.add(ser)
                chosen.append((ser, ser not in corpus_rules))
    return chosen


DOC = """\
<main class="card">
  <h1>gzipt</h1>
  <h2>a stylesheet written by gzip</h2>
  <p>Every rule on this page was generated by a compression algorithm, not a
  person — recombined from real open-source stylesheets and validated by a CSS
  parser. <a href="#">None of it was copied verbatim.</a></p>
  <blockquote>What compresses well is what the model predicts.</blockquote>
  <button>A Button</button>
  <ul><li>first item</li><li>second item</li><li>third item</li></ul>
  <table>
    <tr><th>track</th><th>price</th></tr>
    <tr><td>So What</td><td>0.99</td></tr>
    <tr><td>Blue in Green</td><td>0.99</td></tr>
  </table>
  <form><label><input type="radio" name="r" checked> option</label></form>
</main>
"""


def main():
    corpus = open("data/css/realprops.css", encoding="utf-8", errors="replace").read()
    corpus_rules = C.corpus_rule_set(corpus)
    rules = gather_rules(corpus, corpus_rules)
    n_novel = sum(novel for _, novel in rules)
    css = "\n".join(ser for ser, _ in rules)

    page_pad = "body{font-family:system-ui,sans-serif;background:#f3f4f6;margin:0;padding:2rem;}" \
               ".card{max-width:640px;margin:auto;background:#fff;padding:2rem;" \
               "border-radius:12px;box-shadow:0 10px 40px rgba(0,0,0,.12);}"
    html = (f"<!doctype html><html><head><meta charset='utf-8'><style>\n"
            f"{root_tokens(corpus)}\n/* --- page frame (not generated) --- */\n{page_pad}\n"
            f"/* --- {len(rules)} gzipt-generated rules, {n_novel} novel --- */\n{css}\n"
            f"</style></head><body>{DOC}</body></html>")

    with open("data/css/demo.html", "w") as fh:
        fh.write(html)
    print(f"{len(rules)} valid generated rules ({n_novel} novel) -> data/css/demo.html")

    subprocess.run(["chromium", "--headless", "--disable-gpu", "--no-sandbox",
                    "--hide-scrollbars", "--force-device-scale-factor=2",
                    "--window-size=760,1500", "--default-background-color=FFFFFFFF",
                    "--screenshot=data/css/gzipt_css_demo.png",
                    "data/css/demo.html"],
                   check=True, capture_output=True)
    print("screenshot -> data/css/gzipt_css_demo.png")


if __name__ == "__main__":
    main()
