"""Command-line interface for gzipt — gzip beam-search text generation."""

from __future__ import annotations

import argparse
import sys

from .model import DEFAULT_WINDOW, generate


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="gzipt",
        description="Generate text using gzip as the language model: beam search "
                    "over a corpus that primes the compressor's window.",
    )
    p.add_argument("--corpus", "--prime", dest="corpus", metavar="FILE",
                   help="text file that primes gzip's window — the model's only "
                        "knowledge (generation copies/recombines from it)")
    p.add_argument("--prompt", default="", help="seed text to continue")
    p.add_argument("--length", type=int, default=200, help="bytes to generate (default 200)")

    # Beam-search knobs.
    p.add_argument("--horizon", type=int, default=24,
                   help="bytes looked ahead and committed per beam search "
                        "(default 24; too small collapses, too large just copies)")
    p.add_argument("--beam-width", type=int, default=32,
                   help="partial continuations kept each step (default 32)")
    p.add_argument("--temperature", type=float, default=0.5,
                   help="0 = most-compressible span; >0 samples the final beams "
                        "(default 0.5)")
    p.add_argument("--tail", type=int, default=80,
                   help="generated bytes kept in the scoring context; older output "
                        "is hidden to stop gzip copying itself (default 80)")
    p.add_argument("--no-repeat", type=int, default=8, metavar="N",
                   help="penalize repeating any generated N-gram; the loop guard "
                        "(0 = off, default 8)")
    p.add_argument("--repeat-penalty", type=float, default=4.0,
                   help="bytes added to a candidate's score per repeated n-gram "
                        "(default 4)")

    # Compression / performance knobs.
    p.add_argument("--window", type=int, default=DEFAULT_WINDOW,
                   help=f"corpus bytes shown to gzip, <=32768 (default {DEFAULT_WINDOW})")
    p.add_argument("--level", type=int, default=9, help="gzip level 0-9 (default 9)")
    p.add_argument("--workers", type=int, default=8,
                   help="threads for candidate scoring; zlib releases the GIL (default 8)")
    p.add_argument("--seed", type=int, default=None, help="RNG seed (for --temperature > 0)")

    args = p.parse_args(argv)

    corpus = b""
    if args.corpus:
        with open(args.corpus, "rb") as fh:
            corpus = fh.read()
    prompt = args.prompt.encode("utf-8", errors="replace")

    out = generate(
        corpus, prompt, args.length,
        window=args.window, horizon=args.horizon, beam_width=args.beam_width,
        temperature=args.temperature, tail=args.tail, no_repeat=args.no_repeat,
        repeat_penalty=args.repeat_penalty, level=args.level,
        workers=args.workers, seed=args.seed,
    )

    text = (prompt + out).decode("utf-8", errors="replace")
    sys.stdout.write(text if text.endswith("\n") else text + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
